### ISSUE TITLE
No More Netflix Developer Access

### ISSUE THREAD

**Issue by Owlz** [amalakar/pyflix2#16]
This library seems to be predicated on the ability of the user to sign up for a netflix developer API account. With this functionality removed from Netflix now, is it still possible to connect and play a video via python? Otherwise, it might be a good idea to add a notice to the top of your documentation noting that this library is mostly defunct.

**Comment by fmorrison42** [comment]
I've seen this issue as well. I'm not sure why Netflix took it away. Although, it would be nice if it were possible to just log in. I'm trying to build a DB of all their sub-genre pages for future use. Any thoughts?

**Comment by zahidirfan** [comment]
@amalakar : Any response to this question?

**Comment by amalakar** [comment]
Unfortunately that is the case that netflix is not issuing developer keys anymore. I have updated the README.

http://techblog.netflix.com/2016/08/engineering-trade-offs-and-netflix-api.html

There is nothing we can do I guess.
